blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
# 블로그 앱의 url에 namespace 설정하도록 변경

urlpatterns = [ # url과 뷰 연결
    path('', views.post_list, name='post_list'),
    # '' : 끝에 blog가 오는 url요청이 오면 post_list뷰로 연결시켜주기
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/delete', views.post_delete, name='post_delete'),  # 삭제 기능
    path('post/<int:pk>/comment', views.add_comment_to_post, name='add_comment_to_post'), # 댓글 기능
]

bookmark/urls.py
from django.urls import path
from .views import BookmarkListView, BookmarkCreateView, BookmarkDetailView, BookmarkUpdateView, BookmarkDeleteView

app_name = 'bookmark'
# 북마크 앱의 url에 namespace 설정하도록 변경

urlpatterns = [
    path('', BookmarkListView.as_view(), name = 'list'),
    path('add/', BookmarkCreateView.as_view(), name = 'add'),
    path('detail/<int:pk>/', BookmarkDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', BookmarkUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BookmarkDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')), # 제일먼저 home.urls로 연결하기
    path('polls/', include('polls.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

bookmark/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Bookmark(models.Model):
    site_name = models.CharField(max_length = 100)
    url = models.URLField('Site URL')

    def __str__(self):
        return "이름 : " + self.site_name + ", 주소 : " + self.url  # 객체를 출력할 때 나타날 값

    def get_absolute_url(self):
        return reverse('bookmark:detail', args=[str(self.id)])

bookmark/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView,DeleteView
from django.views.generic.detail import DetailView
from .models import Bookmark
from django.urls import reverse_lazy

# Create your views here.
class BookmarkListView(ListView) :
    model = Bookmark
    paginate_by = 6  # 한 페이지당 6건으로 지정

class BookmarkCreateView(CreateView) :
    model = Bookmark
    fields = ['site_name', 'url']
    success_url = reverse_lazy('bookmark:list')
    template_name_suffix = '_create'

class BookmarkDetailView(DetailView) :
    model = Bookmark

class BookmarkUpdateView(UpdateView) :
    model = Bookmark
    fields = ['site_name','url']
    template_name_suffix = '_update'

class BookmarkDeleteView(DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:list')

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}

{% block title %} Confirm Delete {% endblock %}

{% block content %}
<form action ="" method="post">
    {% csrf_token %} <!-- form 태그 쓸 때 항상 같이 써야함. 외부로부터 공격 막는 용도 -->
    <div class="alert alert-danger">Do you want to delete Bookmark "{{object}}"?</div> <!-- 삭제 전 확인 문구 -->
    <input type="submit" value="Delete" class="btn btn-danger"> <!-- 버튼 추가 -->
</form>
{% endblock %}

bookmark/templates/bookmark/bookmark_create.html
{% extends 'base.html' %}

{% block title %}
Bookmark Add
{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %} <!-- 해커로부터 공격 막기 -->
    {{form.as_p}} <!-- form을 p 태그로 감싸서 렌더링 -->
    <input type="submit" value="Add" class="btn btn-info btn-sm">
</form>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% block title %}
Detail
{% endblock %}

{% block content %}
{{object.site_name}}<br/>
{{object.url}}

<p></p>

<tr>
    <td><a href="{% url 'bookmark:update' pk=bookmark.id %}" class="btn btn-success btn-sm">Modify</a></td>
    <td><a href="{% url 'bookmark:delete' pk=bookmark.id %}" class="btn btn-danger btn-sm">Delete</a> </td>
</tr>

{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}

{% block title %}Bookmark List{% endblock %}

{% block content %}
<div class = "btn-group">
    <a href="{% url 'bookmark:add' %}" class="btn btn-info">Add Bookmark</a>
</div>
<p></p>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Site</th>
            <th scope="col">URL</th>
            <th scope="col">Modify</th>
            <th scope="col">Delete</th>
        </tr>
    </thead>

    <tbody>
        {% for bookmark in object_list %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td><a href="{% url 'bookmark:detail' pk=bookmark.id %}">{{bookmark.site_name}}</a></td>
                <td><a href="{{bookmark.url}}" target="_blank">{{bookmark.url}}</a> </td>
                <td><a href="{% url 'bookmark:update' pk=bookmark.id %}" class="btn btn-success btn-sm">Modify</a></td>
                <td><a href="{% url 'bookmark:delete' pk=bookmark.id %}" class="btn btn-danger btn-sm">Delete</a> </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

{% block pagination %} <!--페이징 기능 -->

{% if is_paginated %} <!-- 지정한 북마크 갯수가 되었을 때 참(True)이 되어서 아래 내용 코드가 실행됨 -->
    <ul class="pagination justify-content-center pagination-sm">
        {% if page_obj.has_previous %} <!-- 이전 페이지 버튼을 만들어주는 것 + (previous 링크텍스트는 탭버튼이 동작하지 않음)-->
            <li class="page-item"> <!-- 이전 페이지가 존재하면 -->
                <!-- tabindex="-1"은 탭으로 이동x 마우스로 클릭할 수 있게 함 -->
                <a class="page-link" href="{% url 'bookmark:list' %}?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
            </li>
        {% else %} <!-- 이전 페이지가 존재하지 않으면 -->
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Previous</a> <!-- #을 링크로 줘서 아무데도 이동하지 않게 함 -->
            </li>
        {% endif %}

        {% for object in page_obj.paginator.page_range %} <!--  page_obj. 객체가 갖고있는 range를 순회 및 page에 할당되는 번호들 추가-->
            <!-- 만약 지금 있는 페이지의 number와 가리키는 페이지의 number가 같을 떄는 클릭이 되지 않도록 함-->
            <li class="page-item {% if page_obj.number == forloop.counter %}disabled{% endif %}">
                <a class="page-link" href="{{ request.path }}?page={{ forloop.counter }}">{{ forloop.counter }}</a> <!-- 하나씩 증가하는 숫자 형태로 페이지가 나오도록 -->
            </li>
        {% endfor %}

        {% if page_obj.has_next %} <!-- 다음 페이지가 존재할 때 next 버튼을 만들어주는 것 -->
            <li class="page-item">
                <a class="page-link" href="{% url 'bookmark:list' %}?page={{ page_obj.next_page_number }}">Next</a>
            </li>
        {% else %} <!-- next 페이지가 없을 때 #을 링크로 줘서 아무데도 이동하지 않게 함-->
            <li class="page-item disabled">
                <a class="page-link" href="#">Next</a>
            </li>
        {% endif %}
    </ul>
{% endif %}

{% endblock %}

bookmark/templates/bookmark/bookmark_update.html
{% extends 'base.html' %}

{% block title %}
Bookmark Add
{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Update" class="btn btn-info btn-sm">
</form>
{% endblock %}