blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
# 블로그 앱의 url에 namespace 설정하도록 변경

urlpatterns = [ # url과 뷰 연결
    path('', views.post_list, name='post_list'),
    # '' : 끝에 blog가 오는 url요청이 오면 post_list뷰로 연결시켜주기
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/delete', views.post_delete, name='post_delete'),  # 삭제 기능
    path('post/<int:pk>/comment', views.add_comment_to_post, name='add_comment_to_post'), # 댓글 기능
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')), # 제일먼저 home.urls로 연결하기
    path('polls/', include('polls.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name='polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:pk>/allresults/', views.AllResultsView.as_view(), name='allresults'), # 전체 결과
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        # 글 날짜가 하루가 지났다면 오래됬다고 체크 (아니라면 최신 글로 체크)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse
from django.views import generic

# Create your views here.
# ★ 함수형 -> 제네릭뷰(클래스) 형식으로 변경
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

class AllResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/allresults.html'

# ★ 함수형
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     #output = ', '.join([q.question_text for q in latest_question_list])
#     #return HttpResponse(output)
#     #return HttpResponse("김혜진(2005905) Hello world!")
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'polls/index.html', context)

# def detail(request, question_id) :
#     #return HttpResponse("You're looking at question %s." % question_id)
#     question = get_object_or_404(Question, pk = question_id)
#     return render(request, 'polls/detail.html', {'question':question})
#
#
# def results(request, question_id) :
#     #response = HttpResponse("You're looking at results of question %s." % question_id)
#     #return response
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question':question})

def vote(request, question_id) :
    #return HttpResponse("You're voting on question %s." % question_id)
    question = get_object_or_404(Question, pk = question_id)
    try :
        selected_choice = question.choice_set.get(pk = request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {'question':question, 'error_message':"You didn't select a choice"})
    else :
        selected_choice.votes +=1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/allresults.html
{% extends 'base.html' %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>{{question.question_text}}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
    {% endfor %}
</ul>

</body>
{% endblock %}

polls/templates/polls/detail.html
{% extends 'base.html' %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{question.question_text}}</h1>
{% if error_message %} <p> <string>{{error_message}}</string> </p> {% endif %}

<form action = "{% url 'polls:vote' question.id %}" method = "post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
    {% endfor %}

    <input type="submit" value="Vote">
</form>

</body>
{% endblock %}

polls/templates/polls/index.html
{% extends 'base.html' %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

</head>
<body>

{% if latest_question_list %}

    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
            <a href=" {% url 'polls:allresults' question.id %}">결과 보기</a> <!-- 전체 결과보기 -->
        {% endfor %}
    </ul>

{% else %}
    <p>No polls are available.</p>
{% endif %}



</body>
{% endblock %}

polls/templates/polls/results.html
{% extends 'base.html' %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>{{question.question_text}}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
    {% endfor %}
</ul>
<a href=" {% url 'polls:detail' question.id %}">Vote again?</a>
</body>
{% endblock %}