blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
# 블로그 앱의 url에 namespace 설정하도록 변경

urlpatterns = [ # url과 뷰 연결
    path('', views.post_list, name='post_list'),
    # '' : 끝에 blog가 오는 url요청이 오면 post_list뷰로 연결시켜주기
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/delete', views.post_delete, name='post_delete'),  # 삭제 기능
    path('post/<int:pk>/comment', views.add_comment_to_post, name='add_comment_to_post'), # 댓글 기능
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')), # 제일먼저 home.urls로 연결하기
    path('polls/', include('polls.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone ## 시간을 사용하기 위해 import 선언

# Create your models here.

class Post(models.Model):   # models.Model을 상속받아서 클래스 형태로 정의
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # author = 저자, 즉 작성한 사람을 의미. 그 사람을 외래키로 설정
    title = models.CharField(max_length=200) # 게시글의 제목 (최대 200까지 가능)
    text = models.TextField() # 게시글의 글 부분
    created_date = models.DateTimeField(default=timezone.now)  # created_date : 블로그가 처음 생성된 시기
    # ↑ DateTimeField 정의 - 기본값으로 timezone.now(현재시간) 설정 즉, 데이터가 추가되는 시간을 받아온다. 어떤 게시글이 처음 생성된 시간
    published_date = models.DateTimeField(blank=True, null=True) # DateTimeField 정의 - blank=True, null=True 설정

    def publish(self):
        self.published_date = timezone.now() # 이 게시글이 게시된 시기
        self.save() # 저장

    def __str__(self):
        return self.title # 타이틀 리턴

class Comment(models.Model): # 댓글
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from .models import Post, Comment

# PostForm이라는 클래스를 정의 -  장고의 forms의 ModelForm을 상속받음
class PostForm(forms.ModelForm): # 장고에서 제공하는 폼 형태 (게시글)

    class Meta: # 이 폼을 만들기위해서 어떤 model이 쓰여야 하는지 장고에 알려주는 구문
        model = Post
        fields = ('title', 'text',) # 폼에 보여질 양식
        # 즉 글의 제목과 내용을 입력받겠다는 말임. 그 외 author은 현재 로그인하고 있는 사람, created_date는 글이 등록된 날짜도 있음

# CommentForm이라는 클래스를 정의 -  장고의 forms의 ModelForm을 상속받음
class CommentForm(forms.ModelForm): # (댓글)

    class Meta: # 이 폼을 만들기위해서 어떤 model이 쓰여야 하는지 장고에 알려주는 구문
        model = Comment
        fields = ('author', 'text',) # 폼에 보여질 양식

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone # 시간을 사용하기 위해 import
from .models import Post, Comment # Post 사용하기 위해 정의
from .forms import PostForm, CommentForm

# Create your views here.

# ★함수형 뷰는 항상 request를 매개변수로 받음
def post_list(request): # 목록에 대한 뷰를 request를 받는 함수형으로 정의
    # posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-created_date') # 최근 글이 위로
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk): # 함수형으로 정의 - 상세페이지이기 때문에 list에서 선택한 글을 DB에서 읽어다가 그 글에 대한 정보를 화면에 출력
    post = get_object_or_404(Post, pk=pk) # get_object_or_404를 이용해서 요청받은 글의 번호(PK값)로 해당되는 글을 찾는다.
    # 모델인 POST에서 PK가 요청받은 PK를 가지고 해당글을 찾아서 변수 post에 넣는다
    return render(request, 'blog/post_detail.html', {'post': post})
    # render함수가 하는 일 - 이렇게 가지고온 post를 갖고 blog/post_detail.html과 함께 reponse로 보냄.

def post_new(request): # 함수형으로 정의 - 블로그 글 추가
    if request.method == "POST": # request에서 가지고 있는 메서드가 POST이면
        # 사용자가 form에 제목이나 글을 입력을 하고 저장을 하면 request 메서드가 POST로 전달이 됨
        form = PostForm(request.POST)
        if form.is_valid(): # is_valid()함수를 통해서 form의 값들이 바른지 체크(바르면 아래내용 실행)
            post = form.save(commit=False) # 받아온 값들을 저장 - commit=False는 바로 저장하지 말라는 것
            post.author = request.user # 저자 = 글을 쓴 사람(유저)
            post.published_date = timezone.now() # 글을 쓴 시간 = 지금 시간
            post.save() # 저장버튼 - 실제로 이 때 db에 저장이 된다.
            return redirect('blog:post_detail', pk=post.pk) # redirect 메서드 호출해서 post_detail로 연결 - 즉 글쓰고 저장완료시 post_detail화면으로 이동하라는 뜻
    else: # request에서 가지고 있는 메서드가 POST가 아니면 (GET이면)
        form = PostForm() # form에 PostForm()을 할당 - 즉 비어있는 form을 보여주라는 뜻 (사용자에게 입력받을 수 있는 폼 형식을 보여줌)
    return render(request, 'blog/post_edit.html', {'form': form}) # render함수를 리턴, post_edit.html을 리턴 및 form 변수에 form을 할당

def post_edit(request, pk): # 함수형으로 정의 - 블로그 글 수정
    post = get_object_or_404(Post, pk=pk) # pk를 가지고 db에서 글의 내용을 가지고 와서 post에 넣음
    if request.method == "POST": # request에서 가지고 있는 메서드가 POST이면
        form = PostForm(request.POST, instance=post) # instance=post를 넣음 - 즉 비어잇는 폼에 post를 담음
        if form.is_valid(): # 받아온 form이 유효한지 확인
            post = form.save(commit=False) # 받아온 값들을 저장 - commit=False는 바로 저장하지 말라는 것
            post.author = request.user # 저자 = 글을 쓴 사람(유저)
            post.published_date = timezone.now() # 글을 쓴 시간 = 지금 시간
            post.save() # 저장버튼 - 실제로 이 때 db에 저장이 된다.
            return redirect('blog:post_detail', pk=post.pk) # redirect 메서드 호출해서 post_detail로 연결 - 즉 글쓰고 저장완료시 post_detail화면으로 이동하라는 뜻

    else: # request에서 가지고 있는 메서드가 POST가 아니면 (GET이면)
        form = PostForm(instance=post) # instance=post를 넣음 - 즉 비어잇는 폼에 post를 담음
    return render(request, 'blog/post_edit.html', {'form': form}) # render함수를 리턴, post_edit.html을 리턴 및 form 변수에 form을 할당

# 삭제 기능
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog:post_list')

# 댓글 기능
def add_comment_to_post(request, pk): # 함수형으로 정의 - 댓글 추가
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST": # request에서 가지고 있는 메서드가 POST이면
        form = CommentForm(request.POST) # 사용자가 form에 제목이나 글을 입력을 하고 저장을 하면 request 메서드가 POST로 전달이 됨
        if form.is_valid(): # form의 값들이 바른지 체크
            comment = form.save(commit=False) # 받아온 값들을 저장 - commit=False는 바로 저장하지 말라는 것
            comment.post = post
            comment.save() # 저장버튼 - 실제로 이 때 db에 저장이 된다
            return redirect('blog:post_detail', pk=post.pk) # redirect 메서드 호출해서 post_detail로 연결
    else: # request에서 가지고 있는 메서드가 POST가 아니면
        form = CommentForm() # form에 CommentForm()을 할당 - 즉 비어있는 댓글 form을 보여주라는 뜻
    return render(request, 'blog/add_comment_to_post.html', {'form': form}) # add_comment_to_post.html을 리턴하고 form 변수에 form을 할당

blog/templates/blog/add_comment_to_post.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
<head>
    <!-- 부트스트랩 이용하여 디자인 바꾸기 -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    <meta charset="UTF-8">

    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">

    <title>Title</title>

</head>
<body>

<div class="page-header">
    {% if user.is_authenticated %} <!-- 로그인한 사람만 글을 등록하게 만들기 -->
    <!-- base.html에 구현해야 모든 화면에서 보이므로 어느곳에서든 글추가 가능 -->
    <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a> <!-- post_new로 연결 및 (+)글 추가 아이콘 생성 -->
    <!--  <a href="{% url 'blog:post_delete' %" class="top-menu"><span class="glyphicon glyphicon-minus"></span></a> </a> 삭제 -->
    {% endif %}
    <h1><a href="{% url 'blog:post_list' %}">HYWU Blog</a></h1>  <!--HYWU Blog 라는 제목의 하이퍼링크 설정 및 post_list로 연결 -->
    <!-- ↑ HYWU Blog 타이틀(제목)을 누르면 항상 메인 post_list로 갈 수 있게 함  -->
</div>


    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
<head>
    <!-- 부트스트랩 이용하여 디자인 바꾸기 -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    <meta charset="UTF-8">

    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">

    <title>Title</title>

</head>
<body>

<div class="page-header">
    {% if user.is_authenticated %} <!-- 로그인한 사람만 글을 등록하게 만들기 -->
    <!-- base.html에 구현해야 모든 화면에서 보이므로 어느곳에서든 글추가 가능 -->
    <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a> <!-- post_new로 연결 및 (+)글 추가 아이콘 생성 -->
    <!--  <a href="{% url 'blog:post_delete' %" class="top-menu"><span class="glyphicon glyphicon-minus"></span></a> </a> 삭제 -->
    {% endif %}
    <h1><a href="{% url 'blog:post_list' %}">HYWU Blog</a></h1>  <!--HYWU Blog 라는 제목의 하이퍼링크 설정 및 post_list로 연결 -->
    <!-- ↑ HYWU Blog 타이틀(제목)을 누르면 항상 메인 post_list로 갈 수 있게 함  -->
</div>

<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% block content %} <!-- 템플릿 태그 사용 - post라는 객체를 하나씩 순회하면서 아래 내용 반복-->
            {% endblock %} <!-- 템플릿 태그 닫기 -->
        </div>
    </div>
</div>

</body>
</html>

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<head>
    <!-- 부트스트랩 이용하여 디자인 바꾸기 -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    <meta charset="UTF-8">

    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">

    <title>Title</title>

</head>
<body>

<div class="page-header">
    {% if user.is_authenticated %} <!-- 로그인한 사람만 글을 등록하게 만들기 -->
    <!-- base.html에 구현해야 모든 화면에서 보이므로 어느곳에서든 글추가 가능 -->
    <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a> <!-- post_new로 연결 및 (+)글 추가 아이콘 생성 -->
    <!--  <a href="{% url 'blog:post_delete' %" class="top-menu"><span class="glyphicon glyphicon-minus"></span></a> </a> 삭제 -->
    {% endif %}
    <h1><a href="{% url 'blog:post_list' %}">HYWU Blog</a></h1>  <!--HYWU Blog 라는 제목의 하이퍼링크 설정 및 post_list로 연결 -->
    <!-- ↑ HYWU Blog 타이틀(제목)을 누르면 항상 메인 post_list로 갈 수 있게 함  -->
</div>



<div class="post">
    {% if post.published_date %} <!-- published_date가 있을 때 -->
        <div class="date"> <!-- date 를 출력  -->
            {{ post.published_date }}
        </div>
    {% endif %}

    {% if user.is_authenticated %} <!-- 로그인한 사람만 글을 등록하게 만들기 -->
    <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a> <!-- 글 수정 -->
    <a class="btn btn-default" href="{% url 'blog:post_delete' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a> <!-- 글 삭제 -->
    <a class="btn btn-default" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add comment</a> <!-- 댓글 -->
    {% endif %}
    <h1>{{ post.title }}</h1>   <!-- 제목 출력 -->
    <p>{{ post.text|linebreaksbr }}</p> <!-- 내용출력, linebreaksbr은 줄바꿈문자가 들어있을때 줄바꿔주는 역할 즉 <br>태그로 변경해주는 역할을 함-->


</div>

<hr>
{% for comment in post.comments.all %} <!-- 댓글 -->
    <div class="comment">
        <div class="date">{{ comment.created_date }}</div> <!-- 댓글 날짜 -->
        <strong>{{ comment.author }}</strong> <!-- 댓글 단 사람 -->
        <p>{{ comment.text|linebreaks }}</p> <!-- 댓글 -->
    </div>
{% empty %} <!-- 비어있는 경우 -->
    <p>아직 작성된 댓글이 없습니다.</p> <!-- 작성된 댓글이 없다고 안내 -->
{% endfor %}

{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<head>
    <!-- 부트스트랩 이용하여 디자인 바꾸기 -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    <meta charset="UTF-8">

    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">

    <title>Title</title>

</head>
<body>

<div class="page-header">
    {% if user.is_authenticated %} <!-- 로그인한 사람만 글을 등록하게 만들기 -->
    <!-- base.html에 구현해야 모든 화면에서 보이므로 어느곳에서든 글추가 가능 -->
    <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a> <!-- post_new로 연결 및 (+)글 추가 아이콘 생성 -->
    <!--  <a href="{% url 'blog:post_delete' %" class="top-menu"><span class="glyphicon glyphicon-minus"></span></a> </a> 삭제 -->
    {% endif %}
    <h1><a href="{% url 'blog:post_list' %}">HYWU Blog</a></h1>  <!--HYWU Blog 라는 제목의 하이퍼링크 설정 및 post_list로 연결 -->
    <!-- ↑ HYWU Blog 타이틀(제목)을 누르면 항상 메인 post_list로 갈 수 있게 함  -->
</div>


    <h1>New post</h1> <!-- 상단에 타이틀 -->
    <form method="POST" class="post-form">{% csrf_token %} <!-- form추가 - form에 대한 메서드를 POST로 / {% csrf_token %} : 해커들의 공격을 막기 위한 토큰 -->
        {{ form.as_p }} <!-- 장고의 model form - form의  form.as_p를 통해 p태그로 묶인 폼형태의 html을 만들기 위함 -->
        <button type="submit" class="save btn btn-default">Save</button> <!-- save 형식의 버튼 추가  -->
    </form>

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<head>
    <!-- 부트스트랩 이용하여 디자인 바꾸기 -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    <meta charset="UTF-8">

    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">

    <title>Title</title>

</head>
<body>

<div class="page-header">
    {% if user.is_authenticated %} <!-- 로그인한 사람만 글을 등록하게 만들기 -->
    <!-- base.html에 구현해야 모든 화면에서 보이므로 어느곳에서든 글추가 가능 -->
    <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a> <!-- post_new로 연결 및 (+)글 추가 아이콘 생성 -->
    <!--  <a href="{% url 'blog:post_delete' %" class="top-menu"><span class="glyphicon glyphicon-minus"></span></a> </a> 삭제 -->
    {% endif %}
    <h1><a href="{% url 'blog:post_list' %}">HYWU Blog</a></h1>  <!--HYWU Blog 라는 제목의 하이퍼링크 설정 및 post_list로 연결 -->
    <!-- ↑ HYWU Blog 타이틀(제목)을 누르면 항상 메인 post_list로 갈 수 있게 함  -->
</div>


{% for post in posts %} <!-- 템플릿 태그 사용 - post라는 객체를 하나씩 순회하면서 아래 내용 반복-->
    <div class="post">
        <div class="date"><p>published: {{ post.published_date }}</p> <!-- post의 published_date -->
        </div>
        <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1> <!-- {상세페이지로 연결하는 링크 생성} + 제목 -->
        <p>{{ post.text|linebreaksbr }}</p> <!-- 내용 -->
        <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.comments.count }}</a> <!-- 댓글 갯수 보여주기 -->
    </div>
{% endfor %} <!-- 템플릿 태그 닫기 -->

{% endblock %}